INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Pedantic Insurance','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Withering Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Recalcitrant Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Recalcitrant Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Inconceivable Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Abominable Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Desperate Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ginormous Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Recalcitrant Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Unbelievable Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Obsequious Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Quiescent Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Evil Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Sleazy Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Abominable Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Unbelievable Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Quiescent Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Pedantic Gym','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Quiescent Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Sleazy Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Jurassic Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Jurassic Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Evil Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Obsequious Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Jurassic Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ginormous Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Jurassic Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Sleazy Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Obsequious Gym','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Violent Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Violent Cable TV','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Inconceivable Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ludicrous Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Yucky Insurance','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Bulimic Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Nuclear Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Unbelievable Gym','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Abominable Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Bulimic Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Recalcitrant Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Obsequious Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Yucky Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ginormous Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Obsequious Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Unbelievable Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ludicrous Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Funky Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Nuclear Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Evil Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Zealous Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Pedantic Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Xenophobic Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Withering Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Funky Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Unbelievable Gas','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Jurassic Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Desperate Gas','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Nuclear Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Gas','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Malevolent Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Inconceivable Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Yucky Water and Sewer','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Xenophobic Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Xenophobic Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Zealous Cable TV','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Inconceivable Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Desperate Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ginormous Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Inconceivable Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ginormous Gas','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Malevolent Water and Sewer','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Abominable Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Desperate Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Yucky Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Malevolent Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Yucky Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Violent Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Funky Gym','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Taciturn Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Yucky Gas','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ludicrous Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Hungry Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Quiescent Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Evil Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Evil Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Recalcitrant Power','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Malevolent Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Unbelievable Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Abominable Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Malevolent Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Jurassic Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ginormous Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Gym','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ludicrous Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Funky Platinum Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Nuclear Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Nuclear Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Nuclear Insurance','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Sleazy Credit Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Withering Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Cosmic Lawn Service','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Hungry Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Bulimic Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Taciturn Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Obsequious Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Violent Saving & Loan','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Kick-ass Plastic Credit','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Taciturn Gas','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Ludicrous Gym','BILL',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Bulimic Gold Card','CC',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Bulimic Credit Union','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Malevolent Bank','CHECKING',0);
INSERT INTO `acct` (`name`, `type`, `version`) VALUES ('Pedantic Credit Card','CC',0);